# Generated by Django 5.2.11 on 2026-02-15 19:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiaryEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("work_summary", models.TextField(max_length=5000)),
                ("hours_worked", models.CharField(max_length=5000)),
                ("show_your_work", models.TextField(blank=True, max_length=5000)),
                ("learnings", models.TextField(blank=True, max_length=5000)),
                ("blockers", models.TextField(blank=True, max_length=5000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
